---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: one-platform-api-catalog-service
  title: API Catalog Microservice
  namespace: devex
  description: Microservice based GraphQL API Backend ecosystem for API Catalog.
  annotations:
    github.com/project-slug: '1-Platform/one-platform'
    servicenow.com/appcode: ONEP-007
  tags:
    - microservice
    - api-catalog
    - developers
    - one-platform
    - nodejs
spec:
  type: service
  lifecycle: production
  owner: group:redhat/one-platform-devs
  system: devex/one-platform
  dependsOn:
    - resource:devex/native-apps-mongodb
  dependencyOf:
    - component:devex/one-platform-api-gateway
