---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: one-platform-user-group-service
  title: User-Group Microservice
  namespace: devex
  description: Microservice based GraphQL API Backend ecosystem for User Group information integrated with the Rover.
  annotations:
    github.com/project-slug: '1-Platform/one-platform'
    backstage.io/techdocs-ref: dir:.
    servicenow.com/appcode: ONEP-001
  tags:
    - microservice
    - user-group
    - developers
    - one-platform
    - nodejs
spec:
  type: service
  lifecycle: production
  owner: group:redhat/one-platform-devs
  system: devex/one-platform
  dependsOn:
    - resource:devex/native-apps-mongodb
  dependencyOf:
    - component:devex/one-platform-api-gateway
