site_name: 'Lighthouse Service'

nav:
  - Getting Started: index.md
  - API Reference: api-reference.md
  - Guide: onboarding-guide.md
  - Overview: overview.md
  - FAQs: faqs.md

plugins:
  - techdocs-core
