---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: one-platform-analytics-service
  title: Analytics Microservice
  namespace: devex
  description: Analytics microservice is used for providing analytics api information for SPAs deployed in One Platform by connecting with Sentry and Pendo.
  annotations:
    github.com/project-slug: '1-Platform/one-platform'
    backstage.io/techdocs-ref: dir:.
    servicenow.com/appcode: ONEP-006
  tags:
    - microservice
    - analytics
    - developers
    - one-platform
    - nodejs
spec:
  type: service
  lifecycle: experimental
  owner: group:redhat/one-platform-devs
  system: devex/one-platform
  dependsOn:
    - resource:devex/native-apps-mongodb
    - resource:devex/one-platform-matomo
  dependencyOf:
    - component:devex/one-platform-api-gateway
