name: Notify the Gchat Group
on:
  pull_request_target:
    types: [opened]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      uses: gautamkrishnar/google-chat-notification@master
      with:
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
