name: CI - Test and Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    - name: Create .env for SPAs
      run: |
        for d in ./packages/*-spa/; do (cd "$d" && cp .test.env .env); done
    - name: Build all packages
      env:
        CI: false
      run: npm run build:packages
    - name: Run tests for all packages
      uses: GabrielBB/xvfb-action@v1
      run: npm run test:packages --if-present
